on:
  push:
    branches:
      - main

name: build, test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build

  test:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    needs: [ build ]
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test
